# Generated by Django 5.1 on 2024-08-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupis',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
