# Generated by Django 5.1.1 on 2024-09-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
