# Generated by Django 5.1 on 2024-08-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_groupis_options_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupis',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chat.groupis'),
        ),
    ]
