# Generated by Django 4.2.8 on 2024-09-02 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 2, 6, 58, 37, 809014, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otpdevice',
            name='otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
