# Generated by Django 5.1.1 on 2024-09-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_myuser_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
