# Generated by Django 5.1.1 on 2024-09-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_myuser_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupis',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
