# Generated by Django 5.1.1 on 2024-09-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_groupis_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupis',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
