# Generated by Django 5.1.1 on 2024-09-19 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_groupis_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupis',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='chat_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
