# Generated by Django 5.1.1 on 2024-09-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
