# Generated by Django 4.2.8 on 2024-09-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_body_alter_message_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='video',
        ),
    ]
