# Generated by Django 5.1.1 on 2024-09-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_myuser_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='public_key',
        ),
    ]
